### ISSUE TITLE
can you make this telegram bot deployed on heroku?

### ISSUE THREAD

**Issue by askfriends** [FindMalek/Syncify#1]

**Comment by FindMalek** [comment]
Hi!
Well Syncify is not a Telegram Bot :/
Syncify is client-based-app.
In the near future, I will be hosting it on a website!
As soon as I finish learning CSS, Js and JSX.

**Comment by askfriends** [comment]
> Hi! Well Syncify is not a Telegram Bot :/ Syncify is client-based-app. In the near future, I will be hosting it on a website! As soon as I finish learning CSS, Js and JSX.

how about creating another version of this repo with telegram bot?

**Comment by FindMalek** [comment]
> > Hi! Well Syncify is not a Telegram Bot :/ Syncify is client-based-app. In the near future, I will be hosting it on a website! As soon as I finish learning CSS, Js and JSX.
> 
> how about creating another version of this repo with telegram bot?

I have no idea how to create Telegram Bot :/
Syncify is an open-source project though!
If you know how to create a Telegram bot then go ahead do it!
You can fork the project.

**Comment by askfriends** [comment]
> > > Hi! Well Syncify is not a Telegram Bot :/ Syncify is client-based-app. In the near future, I will be hosting it on a website! As soon as I finish learning CSS, Js and JSX.
> > 
> > 
> > how about creating another version of this repo with telegram bot?
> 
> I have no idea how to create Telegram Bot :/ Syncify is an open-source project though! If you know how to create a Telegram bot then go ahead do it! You can fork the project.

im also noob into this, but anyway thanks
